// src/internal/codegen/x86_generator.go
package codegen

import (
	"fmt"
	"strings"

	"mikrocompiler/src/internal/ir"
	"mikrocompiler/src/internal/semantic"
)

type X86Generator struct {
	output        strings.Builder
	program       *ir.Program
	symbolTable   *semantic.SymbolTable
	typeSystem    *semantic.TypeSystem
	abi           *ABIInfo
	currentFunc   *ir.Function
	stackFrame    *StackFrame
	labelCounter  int
	stringCounter int
	returnEmitted bool
	// временных переменных IR на стековые адреса
	tempToAddr map[string]string
	// переменных на стековые адреса
	varToAddr     map[string]string
	pendingParams []*ir.Instruction
}

func NewX86Generator(program *ir.Program, symbolTable *semantic.SymbolTable, typeSystem *semantic.TypeSystem) *X86Generator {
	return &X86Generator{
		program:     program,
		symbolTable: symbolTable,
		typeSystem:  typeSystem,
		abi:         NewABIInfo(),
		tempToAddr:  make(map[string]string),
		varToAddr:   make(map[string]string),
	}
}

func (g *X86Generator) Generate() string {
	g.output.Reset()

	g.emit("; Generated by MiniCompiler x86-64 Code Generator")
	g.emit("; System V AMD64 ABI")
	g.emit("")
	g.emit("section .data")
	g.emitStrings()
	g.emit("")
	g.emit("section .text")
	g.emit("extern print_int, print_string, print_newline, read_int, exit")
	g.emit("")

	for _, fn := range g.program.Functions {
		g.generateFunction(fn)
	}

	g.generateStart()

	return g.output.String()
}

func (g *X86Generator) emit(format string, args ...interface{}) {
	g.output.WriteString(fmt.Sprintf(format, args...))
	g.output.WriteString("\n")
}

func (g *X86Generator) emitStrings() {
	for _, gvar := range g.program.Globals {
		if gvar.Type == "string" && gvar.Init != nil {
			if str, ok := gvar.Init.Value.(string); ok {
				label := fmt.Sprintf(".L.str%d", g.stringCounter)
				g.stringCounter++
				g.emit("%s: db \"%s\", 0", label, str)
			}
		}
	}
}

func (g *X86Generator) generateFunction(fn *ir.Function) {
	g.currentFunc = fn
	g.stackFrame = NewStackFrame()
	g.labelCounter = 0
	g.returnEmitted = false
	g.tempToAddr = make(map[string]string)
	g.varToAddr = make(map[string]string)
	g.pendingParams = nil

	g.emit("")
	g.emit("; Function: %s", fn.Name)
	g.emit("global %s", fn.Name)
	g.emit("%s:", fn.Name)

	// Собираем все ALLOCA для выделения памяти
	g.collectAllocations(fn)

	g.generatePrologue(fn)
	g.setupParameters(fn)

	for _, block := range fn.Blocks {
		g.generateBasicBlock(block)
	}

	if !g.returnEmitted {
		g.emit("    xor eax, eax")
		g.generateEpilogue()
	}
}

func (g *X86Generator) collectAllocations(fn *ir.Function) {
	// маппим обычные переменные
	for varName := range fn.Locals {
		if _, exists := g.varToAddr[varName]; !exists {
			loc := g.stackFrame.AllocateVar(varName, 4)
			g.varToAddr[varName] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
		}
	}

	// Затем временные переменные из ALLOCA и другие используемые адреса
	for _, block := range fn.Blocks {
		for _, inst := range block.Instructions {
			// ALLOCA инструкции
			if inst.Opcode == ir.OpAlloca && inst.Dest != nil {
				name := inst.Dest.Name
				if _, exists := g.tempToAddr[name]; !exists {
					if _, exists := g.varToAddr[name]; !exists {
						loc := g.stackFrame.AllocateVar(name, 4)
						g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
					}
				}
			}
			// Для CALL инструкций добавляем слот для возвращаемого значения
			if inst.Opcode == ir.OpCall && inst.Dest != nil {
				name := inst.Dest.Name
				if _, exists := g.tempToAddr[name]; !exists {
					if _, exists := g.varToAddr[name]; !exists {
						loc := g.stackFrame.AllocateVar(name, 4)
						g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
					}
				}
			}
			// Для RETURN с значением
			if inst.Opcode == ir.OpRet && inst.Src1 != nil {
				name := inst.Src1.Name
				if name != "" {
					if _, exists := g.tempToAddr[name]; !exists {
						if _, exists := g.varToAddr[name]; !exists {
							loc := g.stackFrame.AllocateVar(name, 4)
							g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
						}
					}
				}
			}
		}
	}

	// Если после всех аллокаций стек пуст, но есть вызовы функций, добавляем слот
	if g.stackFrame.MaxOffset == 0 && g.hasFunctionCalls(fn) {
		g.stackFrame.AllocateVar("_padding", 8)
	}
}

func (g *X86Generator) getOperandAddr(op *ir.Operand) string {
	if op == nil {
		return "rbp - 4"
	}

	switch op.Type {
	case ir.OperandVar:
		// Проверяем varToAddr
		if addr, ok := g.varToAddr[op.Name]; ok {
			return addr
		}
		// Проверяем tempToAddr
		if addr, ok := g.tempToAddr[op.Name]; ok {
			return addr
		}
		// Проверяем stackFrame
		loc := g.stackFrame.LocalVars[op.Name]
		if loc != nil {
			addr := fmt.Sprintf("rbp - %d", -loc.StackOffset)
			g.varToAddr[op.Name] = addr
			return addr
		}
		// Новый слот для переменной
		loc = g.stackFrame.AllocateVar(op.Name, 4)
		addr := fmt.Sprintf("rbp - %d", -loc.StackOffset)
		g.varToAddr[op.Name] = addr
		return addr

	case ir.OperandTemp:
		if addr, ok := g.tempToAddr[op.Name]; ok {
			return addr
		}
		// Новый слот для временной переменной
		loc := g.stackFrame.AllocateVar(op.Name, 4)
		addr := fmt.Sprintf("rbp - %d", -loc.StackOffset)
		g.tempToAddr[op.Name] = addr
		return addr

	default:
		return fmt.Sprintf("rbp - %d", -(g.stackFrame.MaxOffset + 8))
	}
}

func (g *X86Generator) generatePrologue(fn *ir.Function) {
	g.emit("    push rbp")
	g.emit("    mov rbp, rsp")

	stackSize := g.stackFrame.GetStackSize()
	// Выравниваем по 16 байт
	if stackSize%16 != 0 {
		stackSize += 16 - (stackSize % 16)
	}
	if stackSize == 0 && g.hasFunctionCalls(fn) {
		stackSize = 16
	}
	if stackSize > 0 {
		g.emit("    sub rsp, %d", stackSize)
	}
}

func (g *X86Generator) hasFunctionCalls(fn *ir.Function) bool {
	for _, block := range fn.Blocks {
		for _, inst := range block.Instructions {
			if inst.Opcode == ir.OpCall {
				return true
			}
		}
	}
	return false
}

func (g *X86Generator) setupParameters(fn *ir.Function) {
	if len(fn.Params) == 0 {
		return
	}

	for i, param := range fn.Params {
		if reg, ok := g.abi.GetIntParamReg(i); ok {
			addr := g.getOperandAddr(&ir.Operand{Type: ir.OperandVar, Name: param.Name})
			reg32 := string(GetReg32(reg))
			g.emit("    mov [%s], %s", addr, reg32)
		}
	}
}

func (g *X86Generator) generateBasicBlock(block *ir.BasicBlock) {
	if block.Label != "entry" {
		g.emit("%s:", block.Label)
	}

	for _, inst := range block.Instructions {
		g.generateInstruction(inst)
	}
}

func (g *X86Generator) generateInstruction(inst *ir.Instruction) {
	switch inst.Opcode {
	case ir.OpAlloca:
		return

	case ir.OpParam:
		// Сохраняем PARAM инструкции для последующего CALL
		g.pendingParams = append(g.pendingParams, inst)
		return

	case ir.OpAdd, ir.OpSub, ir.OpMul, ir.OpAnd, ir.OpOr:
		g.emitBinaryOp(inst)
	case ir.OpDiv:
		g.emitDivMod(inst, false)
	case ir.OpMod:
		g.emitDivMod(inst, true)
	case ir.OpNeg:
		g.emitUnaryOp(inst, "neg")
	case ir.OpNot:
		g.emitNot(inst)
	case ir.OpCmpEq, ir.OpCmpNe, ir.OpCmpLt, ir.OpCmpLe, ir.OpCmpGt, ir.OpCmpGe:
		g.emitComparison(inst)
	case ir.OpLoad:
		g.emitLoad(inst)
	case ir.OpStore:
		g.emitStore(inst)
	case ir.OpJmp:
		g.emit("    jmp %s", inst.Src1.Name)
	case ir.OpJmpIf:
		g.emit("    cmp eax, 1")
		g.emit("    je %s", inst.Src2.Name)
	case ir.OpJmpIfNot:
		g.emit("    cmp eax, 0")
		g.emit("    je %s", inst.Src2.Name)
	case ir.OpCall:
		g.emitCallWithParams(inst)
		g.pendingParams = nil // очищаем буфер
	case ir.OpRet:
		g.emitReturn(inst)
	case ir.OpMove:
		g.emitMove(inst)
	}
}

func (g *X86Generator) emitBinaryOp(inst *ir.Instruction) {
	opMap := map[ir.Opcode]string{
		ir.OpAdd: "add",
		ir.OpSub: "sub",
		ir.OpMul: "imul",
		ir.OpAnd: "and",
		ir.OpOr:  "or",
	}

	op, ok := opMap[inst.Opcode]
	if !ok {
		return
	}

	// Загружаем первый операнд в eax
	g.loadToRegister("eax", inst.Src1)

	// Второй
	g.loadToRegister("ecx", inst.Src2)

	// Выполняем
	g.emit("    %s eax, ecx", op)

	// Сохраняем результат
	g.storeFromRegister("eax", inst.Dest)
}

func (g *X86Generator) emitDivMod(inst *ir.Instruction, isMod bool) {
	g.loadToRegister("eax", inst.Src1)
	g.emit("    cdq")
	g.loadToRegister("ecx", inst.Src2)
	g.emit("    idiv ecx")

	if isMod {
		g.storeFromRegister("edx", inst.Dest)
	} else {
		g.storeFromRegister("eax", inst.Dest)
	}
}

func (g *X86Generator) emitUnaryOp(inst *ir.Instruction, op string) {
	g.loadToRegister("eax", inst.Src1)
	g.emit("    %s eax", op)
	g.storeFromRegister("eax", inst.Dest)
}

func (g *X86Generator) emitNot(inst *ir.Instruction) {
	g.loadToRegister("eax", inst.Src1)
	g.emit("    cmp eax, 0")
	g.emit("    sete al")
	g.emit("    movzx eax, al")
	g.storeFromRegister("eax", inst.Dest)
}

func (g *X86Generator) emitComparison(inst *ir.Instruction) {
	condMap := map[ir.Opcode]string{
		ir.OpCmpEq: "e",
		ir.OpCmpNe: "ne",
		ir.OpCmpLt: "l",
		ir.OpCmpLe: "le",
		ir.OpCmpGt: "g",
		ir.OpCmpGe: "ge",
	}

	condition, ok := condMap[inst.Opcode]
	if !ok {
		return
	}

	g.loadToRegister("eax", inst.Src1)
	g.loadToRegister("ecx", inst.Src2)
	g.emit("    cmp eax, ecx")
	g.emit("    set%s al", condition)
	g.emit("    movzx eax, al")
	g.storeFromRegister("eax", inst.Dest)
}

func (g *X86Generator) emitLoad(inst *ir.Instruction) {
	addr := g.getOperandAddr(inst.Src1)
	g.emit("    mov eax, [%s]", addr)
	g.storeFromRegister("eax", inst.Dest)
}

func (g *X86Generator) emitStore(inst *ir.Instruction) {
	addr := g.getOperandAddr(inst.Src1)

	if inst.Src2.Type == ir.OperandLiteral {
		if val, ok := inst.Src2.GetIntValue(); ok {
			g.emit("    mov dword [%s], %d", addr, val)
		} else if val, ok := inst.Src2.GetBoolValue(); ok {
			if val {
				g.emit("    mov dword [%s], 1", addr)
			} else {
				g.emit("    mov dword [%s], 0", addr)
			}
		} else {
			g.emit("    mov dword [%s], %v", addr, inst.Src2.Value)
		}
	} else {
		g.loadToRegister("eax", inst.Src2)
		g.emit("    mov [%s], eax", addr)
	}
}

func (g *X86Generator) emitCallWithParams(inst *ir.Instruction) {
	for _, param := range g.pendingParams {
		paramIdx := 0
		if param.Src1 != nil {
			if val, ok := param.Src1.GetIntValue(); ok {
				paramIdx = val
			}
		}

		if paramIdx < 6 {
			reg := g.abi.IntParamRegs[paramIdx]
			g.loadToRegister(string(GetReg32(reg)), param.Src2)
		}
	}

	g.emit("    call %s", inst.Src1.Name)

	if inst.Dest != nil {
		g.storeFromRegister("eax", inst.Dest)
	}
}

func (g *X86Generator) emitReturn(inst *ir.Instruction) {
	if inst.Src1 != nil {
		g.loadToRegister("eax", inst.Src1)
	}

	g.returnEmitted = true

	// Восстанавливаем стек перед возвратом
	stackSize := g.stackFrame.GetStackSize()
	if stackSize > 0 {
		g.emit("    mov rsp, rbp")
	}
	g.emit("    pop rbp")
	g.emit("    ret")
}

func (g *X86Generator) emitMove(inst *ir.Instruction) {
	g.loadToRegister("eax", inst.Src1)
	g.storeFromRegister("eax", inst.Dest)
}

func (g *X86Generator) generateEpilogue() {
	stackSize := g.stackFrame.GetStackSize()
	if stackSize > 0 {
		g.emit("    mov rsp, rbp")
	}
	g.emit("    pop rbp")
	g.emit("    ret")
}

func (g *X86Generator) generateStart() {
	hasMain := false
	for _, fn := range g.program.Functions {
		if fn.Name == "main" {
			hasMain = true
			break
		}
	}

	if hasMain {
		g.emit("")
		g.emit("global _start")
		g.emit("_start:")
		g.emit("    xor rbp, rbp")
		g.emit("    call main")
		g.emit("    mov rdi, rax")
		g.emit("    call exit")
	}
}

func (g *X86Generator) loadToRegister(reg string, op *ir.Operand) {
	if op == nil {
		g.emit("    xor %s, %s", reg, reg)
		return
	}

	switch op.Type {
	case ir.OperandLiteral:
		if val, ok := op.GetIntValue(); ok {
			g.emit("    mov %s, %d", reg, val)
		} else if val, ok := op.GetBoolValue(); ok {
			if val {
				g.emit("    mov %s, 1", reg)
			} else {
				g.emit("    xor %s, %s", reg, reg)
			}
		} else {
			g.emit("    mov %s, %v", reg, op.Value)
		}

	case ir.OperandVar, ir.OperandTemp:
		addr := g.getOperandAddr(op)
		g.emit("    mov %s, [%s]", reg, addr)

	default:
		g.emit("    mov %s, %s", reg, op.Name)
	}
}

func (g *X86Generator) storeFromRegister(reg string, dest *ir.Operand) {
	if dest == nil {
		return
	}

	switch dest.Type {
	case ir.OperandVar, ir.OperandTemp:
		addr := g.getOperandAddr(dest)
		g.emit("    mov [%s], %s", addr, reg)
	}
}
