package codegen

import (
	"fmt"
	"strings"

	"mikrocompiler/src/internal/ir"
	"mikrocompiler/src/internal/semantic"
)

type X86Generator struct {
	output        strings.Builder
	program       *ir.Program
	symbolTable   *semantic.SymbolTable
	typeSystem    *semantic.TypeSystem
	abi           *ABIInfo
	currentFunc   *ir.Function
	stackFrame    *StackFrame
	labelManager  *LabelManager
	exprGenerator *ExpressionGenerator
	cfGenerator   *ControlFlowGenerator
	returnEmitted bool
	stringCounter int
	// временных переменных IR на стековые адреса
	tempToAddr map[string]string
	// переменных на стековые адреса
	varToAddr     map[string]string
	pendingParams []*ir.Instruction
}

func NewX86Generator(program *ir.Program, symbolTable *semantic.SymbolTable, typeSystem *semantic.TypeSystem) *X86Generator {
	gen := &X86Generator{
		program:     program,
		symbolTable: symbolTable,
		typeSystem:  typeSystem,
		abi:         NewABIInfo(),
		tempToAddr:  make(map[string]string),
		varToAddr:   make(map[string]string),
	}

	gen.labelManager = NewLabelManager()
	gen.exprGenerator = NewExpressionGenerator(gen, gen.labelManager)
	gen.cfGenerator = NewControlFlowGenerator(gen, gen.labelManager, gen.exprGenerator)

	return gen
}

func (g *X86Generator) Generate() string {
	g.output.Reset()
	g.labelManager.Reset()
	g.stringCounter = 0

	g.emit("; Generated by MiniCompiler x86-64 Code Generator")
	g.emit("; System V AMD64 ABI")
	g.emit("; Sprint 6: Control Flow & Short-Circuit Evaluation")
	g.emit("")
	g.emit("section .data")
	g.emitStrings()
	g.emit("")
	g.emit("section .text")
	g.emit("extern print_int, print_string, print_newline, read_int, exit")
	g.emit("")

	for _, fn := range g.program.Functions {
		g.generateFunction(fn)
	}

	g.generateStart()

	return g.output.String()
}

func (g *X86Generator) emit(format string, args ...interface{}) {
	g.output.WriteString(fmt.Sprintf(format, args...))
	g.output.WriteString("\n")
}

func (g *X86Generator) emitStrings() {
	for _, gvar := range g.program.Globals {
		if gvar.Type == "string" && gvar.Init != nil {
			if str, ok := gvar.Init.Value.(string); ok {
				label := g.labelManager.StringLabel(g.stringCounter)
				g.stringCounter++
				g.emit("%s: db \"%s\", 0", label, str)
			}
		}
	}
}

func (g *X86Generator) generateFunction(fn *ir.Function) {
	g.currentFunc = fn
	g.stackFrame = NewStackFrame()
	g.returnEmitted = false
	g.tempToAddr = make(map[string]string)
	g.varToAddr = make(map[string]string)
	g.pendingParams = nil

	g.emit("")
	g.emit("; Function: %s", fn.Name)
	g.emit("global %s", fn.Name)
	g.emit("%s:", fn.Name)

	// Собираем все ALLOCA для выделения памяти
	g.collectAllocations(fn)

	g.cfGenerator.GenerateFunctionPrologue(fn)
	g.setupParameters(fn)

	for _, block := range fn.Blocks {
		g.cfGenerator.GenerateBasicBlock(block)
	}

	if !g.returnEmitted {
		g.emit("    xor eax, eax")
		g.cfGenerator.GenerateFunctionEpilogue()
	}
}

func (g *X86Generator) collectAllocations(fn *ir.Function) {
	// маппим обычные переменные
	for varName := range fn.Locals {
		if _, exists := g.varToAddr[varName]; !exists {
			loc := g.stackFrame.AllocateVar(varName, 4)
			g.varToAddr[varName] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
		}
	}

	// Затем временные переменные из ALLOCA и другие используемые адреса
	for _, block := range fn.Blocks {
		for _, inst := range block.Instructions {
			// ALLOCA инструкции
			if inst.Opcode == ir.OpAlloca && inst.Dest != nil {
				name := inst.Dest.Name
				if _, exists := g.tempToAddr[name]; !exists {
					if _, exists := g.varToAddr[name]; !exists {
						loc := g.stackFrame.AllocateVar(name, 4)
						g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
					}
				}
			}
			// Для CALL инструкций добавляем слот для возвращаемого значения
			if inst.Opcode == ir.OpCall && inst.Dest != nil {
				name := inst.Dest.Name
				if _, exists := g.tempToAddr[name]; !exists {
					if _, exists := g.varToAddr[name]; !exists {
						loc := g.stackFrame.AllocateVar(name, 4)
						g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
					}
				}
			}
			// Для PHI инструкций
			if inst.Opcode == ir.OpPhi && inst.Dest != nil {
				name := inst.Dest.Name
				if _, exists := g.tempToAddr[name]; !exists {
					if _, exists := g.varToAddr[name]; !exists {
						loc := g.stackFrame.AllocateVar(name, 4)
						g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
					}
				}
			}
			// Для RETURN с значением
			if inst.Opcode == ir.OpRet && inst.Src1 != nil {
				name := inst.Src1.Name
				if name != "" {
					if _, exists := g.tempToAddr[name]; !exists {
						if _, exists := g.varToAddr[name]; !exists {
							loc := g.stackFrame.AllocateVar(name, 4)
							g.tempToAddr[name] = fmt.Sprintf("rbp - %d", -loc.StackOffset)
						}
					}
				}
			}
		}
	}

	// Если после всех аллокаций стек пуст, но есть вызовы функций, добавляем слот
	if g.stackFrame.MaxOffset == 0 && g.hasFunctionCalls(fn) {
		g.stackFrame.AllocateVar("_padding", 8)
	}
}

func (g *X86Generator) getOperandAddr(op *ir.Operand) string {
	if op == nil {
		return "rbp - 4"
	}

	switch op.Type {
	case ir.OperandVar:
		if addr, ok := g.varToAddr[op.Name]; ok {
			return addr
		}
		if addr, ok := g.tempToAddr[op.Name]; ok {
			return addr
		}
		loc := g.stackFrame.LocalVars[op.Name]
		if loc != nil {
			addr := fmt.Sprintf("rbp - %d", -loc.StackOffset)
			g.varToAddr[op.Name] = addr
			return addr
		}
		loc = g.stackFrame.AllocateVar(op.Name, 4)
		addr := fmt.Sprintf("rbp - %d", -loc.StackOffset)
		g.varToAddr[op.Name] = addr
		return addr

	case ir.OperandTemp:
		if addr, ok := g.tempToAddr[op.Name]; ok {
			return addr
		}
		loc := g.stackFrame.AllocateVar(op.Name, 4)
		addr := fmt.Sprintf("rbp - %d", -loc.StackOffset)
		g.tempToAddr[op.Name] = addr
		return addr

	default:
		return fmt.Sprintf("rbp - %d", -(g.stackFrame.MaxOffset + 8))
	}
}

func (g *X86Generator) hasFunctionCalls(fn *ir.Function) bool {
	for _, block := range fn.Blocks {
		for _, inst := range block.Instructions {
			if inst.Opcode == ir.OpCall {
				return true
			}
		}
	}
	return false
}

func (g *X86Generator) setupParameters(fn *ir.Function) {
	if len(fn.Params) == 0 {
		return
	}

	for i, param := range fn.Params {
		if reg, ok := g.abi.GetIntParamReg(i); ok {
			addr := g.getOperandAddr(&ir.Operand{Type: ir.OperandVar, Name: param.Name})
			reg32 := string(GetReg32(reg))
			g.emit("    mov [%s], %s", addr, reg32)
		}
	}
}

func (g *X86Generator) generateStart() {
	hasMain := false
	for _, fn := range g.program.Functions {
		if fn.Name == "main" {
			hasMain = true
			break
		}
	}

	if hasMain {
		g.emit("")
		g.emit("global _start")
		g.emit("_start:")
		g.emit("    xor rbp, rbp")
		g.emit("    call main")
		g.emit("    mov rdi, rax")
		g.emit("    call exit")
	}
}

func (g *X86Generator) loadToRegister(reg string, op *ir.Operand) {
	if op == nil {
		g.emit("    xor %s, %s", reg, reg)
		return
	}

	switch op.Type {
	case ir.OperandLiteral:
		if val, ok := op.GetIntValue(); ok {
			g.emit("    mov %s, %d", reg, val)
		} else if val, ok := op.GetBoolValue(); ok {
			if val {
				g.emit("    mov %s, 1", reg)
			} else {
				g.emit("    xor %s, %s", reg, reg)
			}
		} else {
			g.emit("    mov %s, %v", reg, op.Value)
		}

	case ir.OperandVar, ir.OperandTemp:
		addr := g.getOperandAddr(op)
		g.emit("    mov %s, [%s]", reg, addr)

	default:
		g.emit("    mov %s, %s", reg, op.Name)
	}
}

func (g *X86Generator) storeFromRegister(reg string, dest *ir.Operand) {
	if dest == nil {
		return
	}

	switch dest.Type {
	case ir.OperandVar, ir.OperandTemp:
		addr := g.getOperandAddr(dest)
		g.emit("    mov [%s], %s", addr, reg)
	}
}
